### PR TITLE
Add support for ECL

### PR DESCRIPTION
**Pull request by dkochmanski**
This pull requests makes cl-forth load on ECL. I did not perform any further tests though.

### CODE REVIEW

**Comment by gmpalter** [comment]
What version of ECL are you using and what version of ASDF does it bundle?

I'm using ECL 24.5.10 which bundles ASDF 3.1.8.10 and, apparently, `asdf:registered-system` is already exported.

**Comment by gmpalter** [comment]
I just committed your changes with some minor tweaks in e8aafa1e02b3bf6abd49cfafdc4f9f2deb3afe7a.

**Comment by gmpalter** [comment]
I opened [ECL issue 767](https://gitlab.com/embeddable-common-lisp/ecl/-/issues/767) to address an apparent ECL compiler bug which causes the Forth test suite to fail.

**Comment by dkochmanski** [comment]
Hey! Thanks for looking into this. I've commited ASDF fix and bumped its version in ECL on 2024-10-07 (and exported this symbol). It works on ECL devel branch, but on the lastest release (from 2024-05-10) this symbol is not exported.

Thanks for reporting a bug, I'll look into it when I'm done with other pending tasks.

**Pull request closed without merging**
